# Generated by Django 3.0.8 on 2021-06-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendata',
            name='current_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tokendata',
            name='market_cap',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
