# Generated by Django 3.0.8 on 2021-06-06 16:01

from django.db import migrations
from django.conf import settings


def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')
    domain = 'dogefather.space'

    SiteModel.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': domain,
                  'name': domain}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210606_1404'),
        ('sites', '0002_alter_domain_unique'),  # Required to reference `sites` in `apps.get_model()`
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
