FROM python:3.8-slim-buster

ENV PATH /usr/local/bin:$PATH
ENV APP_HOME=/usr/src/app

RUN mkdir -p $APP_HOME
RUN mkdir $APP_HOME/static_cdn
RUN mkdir $APP_HOME/media_cdn
RUN mkdir $APP_HOME/db
WORKDIR $APP_HOME

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .

RUN apt-get -y update \
    && apt-get -y install locales \
    && apt-get -y install ca-certificates netbase \
    && pip3 install --no-cache-dir --upgrade pip setuptools==49.6.0 \
    && pip3 install -r requirements.txt

COPY . .

